sudo: required
language: java
jdk: oraclejdk8

env:
  global:
  - secure: "oDWnV5o445/Jcmib2H4QYI3Yxdw3qOlrC4nwqB+V6lKUaFseTJJpNfSEEbGyZnVlSA/1mJ5braS1/LWXbdHNgPMRl5Su19/d2AjSSGhVuhif/KxnYv4Z/Ts2Jt0WnqkN/xymxdWWX7infs+5tWUovnTKDtQF180k1Vm21I0MfPnZhdPSAbm84hg/x2gNUzIPtPj+DE5xozhlkoHyzz7adQlk3G0pinl9uoV0/Z5a5evWCahtwdNTxcztM+dGCuSHK+h2xotQ5rNzm8fLfGddCLSUK7hGzOThnwvfxnc+xxRIufHTejwZf4xCahqt7+L/FobmkwVjc+N32GljMe+upPYDRqm6TqoUbIyQiIcLEFgK5Alx7kxdi6JIm00JFVNKDIVd4Cnh5nH5XqrjczI3bHEc6PIcT9bKww71A6A3kL9d8VvT/B0AzDLnlnPgxrVzO20cf1dt5eH7d9sTkJZiDkRt0iK3GhPOvWkUw8Q3Zcm9B2rCEfALb439hQ92LuZvGS6mg9YJEypvBiZnRz0deY/kzdiKGHUh58BM116+C2/a0g43K53+trmTWRrqRssefp3a/bjjEMk1fVTpGvHSHHEGbfn7iwbgHzkaG5oEwM2itOo/6NeqVlfmsEaLQcyTHjIFxiK3/RaHaj/BC1NgmULfoEZfaMMD9l5wPURjatA="
  - secure: "ESYMgF93IuDAam+sv1Doe8M6tin/gFkxR0i/nBm7JuaP+QBxCtLTxBZPIHE8T3TkZbIToCMtPC+74C8b08cYI+biA1BzawchuMZ6VZaMhlDzWEbD2vvl5PKCgtHZrj/w2/Gn7TZujuu11rF0t5qA4kbQDhIWSB0F92QJpkjKQa3f+udMnC4H9ud82m41gjAt9SB3HP7PESfRpaB+38qX94C/7n3IpZP6jzdZc1mpnyFOvqsXex3jkHRocOVnfgQN0g5wl8Dv9yER2zrfXVVJhQYrgHSDxsS7a/mOvlY+3EXFTBHQ3zB3b/5S2/ciPFVxOExz04hZPBY/HJ7swOrOAc28riQjbZsHxTlNIYQ82KaWdaCEPLTyqn9fTGxGSCEMIXKD1LlB4//4MnpqRo7KCg41089sy4xvF21Jm0GDZnwGSsWZyGPEB4844ktD8nOh+Ud7hNmi5JA5Kaq/0TaLgRnHlxKP0KkKTtbFcQhb6OTp1rQmmh+Lnyla+cyyPtnyTQzA3PLDFMrOKfhCyeCV86A3F3Vpy23lOK0eoYaHvwMRapp+mWjmjI5CKd6N8uwtfBsFG4Zrur4x4T53Zmv6W0nNBWLpK9W6CakFq4kpaLmYXuS4unn0KMRLZRlwrORLToNC9U7RA0okLtfFwd6mQe7SrVOVmeHcni03u2qQYBU="

addons:
  sonarcloud:
    organization: "sivaprasadreddy-github"
    token:
      secure: $SONAR_TOKEN

script:
  - ./mvnw clean verify
  - ./mvnw sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: sivalabs-sb2s
