sudo: required
language: java
jdk: oraclejdk8

addons:
  sonarcloud:
    organization: "sivaprasadreddy-github"
    token:
      secure: $SONAR_TOKEN

script:
  - ./mvnw clean verify
  - ./mvnw sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: sivalabs-sb2s
